parse:
  count_from: "2026-03-02" # Понедельник, числитель
  numbers_to_days:
    0: 'Понедельник'
    1: 'Вторник'
    2: 'Среда'
    3: 'Четверг'
    4: 'Пятница'
    5: 'Суббота'
    6: 'Воскресенье'
  week_days:
    - 'Понедельник'
    - 'Вторник'
    - 'Среда'
    - 'Четверг'
    - 'Пятница'
    - 'Суббота'
    - 'Воскресенье'

administration:
  admins:
    - 6028124153

database:
  study_levels:
    - "СПО"
    - "Бакалавриат"
    - "Магистратура"

commands:
  start: "Регистрация"
  register: "Регистрация / смена группы"
  today: "Показать расписание на сегодня"
  week: "Показать расписание на неделю"
  shedule: "Расписание на произвольный день"
  links: "Контакты математического факультета"

text:
  # user-output
  new_user: "Здравствуй, математик!\nПройди небольшую регистрацию и сможешь наблюдать свое расписание.\n\nВыбери свою ступень образования:"
  already_register: "Perfecto! Что будем делать?"
  select_year: "Замечательно!\nВыбери свой курс:"
  select_group: "Превосходно!!!\nВыбери своё направление:"
  done_register: "Гениально!!!!! Вы успешно зарегестрировались в сервисе.\nЧто делаем дальше?"

  # admin-panel
  admin_title: "Админ-панель"
  admin_add_group: "Введите ступень обучения, курс, код направления (для отображения). Прим: `СПО 2 ИСИП2`"
  invalid_data: "Неправильный формат. Пожалуста попробуйте ещё:"
  success_operation: "Успешно!\nЧто делаем дальше?"

  links: |
    1. <b>Деканат</b> (каб. 333а) | Тел: 2-208-460; 2-208-553
    2. КАиММГ (каб. 334) | Тел: 2-208-641
    3. КМА (каб. 332) | Тел: 2-208-690
    4. КММ (каб. 322) | Тел: 2-208-364
    5. КТФ (каб. 324) | Тел: 2-208-665
    6. КУЧП (каб. 327, 308) | Тел: 2-208-618
    7. КФА (каб. 225) | Тел: 2-208-771

    Сообщить об ошибке: @mlhv_artem

#     sokr = {
#         "Математический": "Мат.",
#         "Ф   и   з   к   у   л   ь   т   у   р   а": "Физкультура",
#         "Технология программирования и работа на ЭВМ": "ТП и работа на ЭВМ",
#         "Математическая": "Мат.",
#         "Ф И З К У Л Ь Т У Р А": "Физкультура ",
#         "Ф и з к у л ь т у р а": "Физкультура ",
#         "Дополнительные": "Доп. ",
#         "Технология программирования": "ТП ",
#         "Экономика и финансовая грамотность": "Экономика ",
#         "Основы информационной безопасности": "Основы инф. без. ",
#         "Введение в компьютерную лингвистику": "Комп. лингвистика ",
#         "Комплексный": "Компл. ",
#         "В О Е Н Н А Я": "Военная ",
#         "П О Д Г О Т О В К А": "подготовка ",
#         "В о е н н а я": "Военная ",
#         "п о д г о т о в к а": "подготовка ",
#         "Деловое общение и культура речи": "Деловое общение ",
#         "Теоретическая механика": "Теор. мех. ",
#         "Теория вероятностей": "Теор. вер. ",
#         "Основы функционального анализа": "Основы Функ. ана. ",
#         "Дискретная математика": "Дискретка ",
#         "Функциональный анализ": "Функан ",
#         "Базы данных": "БД ",
#         "Уравнения с частными производными": "УЧП ",
#         "Математические": "Мат ",
#         "мехнических": "мех ",
#         "Математическое": "Мат ",
#         "Теория случайных процессов и основы теории массового обслуживания": "ТСП и основы ТМО ",
#         "Информационные технологии и вычислительные средства в матмоделировании": "Спецкурс ",
#         "статистика": "стат. ",
#         "Уравнения математической физики": "УМФ ",
#         "Методы социально-экономического прогнозирования": "Спецкурс ",
#         "математической": "мат. ",
#         "Уравнения": "Ур. ",
#         "Устойчивость решений дифференциальных уравнений": "Спецкурс ",
#         "Методы функционального анализа в теории многообразий и расслоений": "Спецкурс ",
#         "дифференциальными": "дифф. "
#     }