class BaseBotError(Exception): ...


class NotFoundError(BaseBotError): ...

class AlreadyExistError(BaseBotError): ...


class UserNotFoundError(NotFoundError): ...

class GroupNotFoundError(NotFoundError): ...


class UserAlreadyExistsError(AlreadyExistError): ...

class GroupAlreadyExistsError(AlreadyExistError): ...

class TeacherAlreadyExistsError(UserAlreadyExistsError): ...